MNT: rerender
conda-forge/ucx-split-feedstock pull request #87
Opened 2021-03-23 02:47 UTC by conda-forge-linter

Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #86.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #86

2021-03-23 02:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-03-23 02:50 UTC, jakirkham requested changes
Seeing some weird issues from re-rendering. Flagging them in the review comments below

2021-03-23 02:50 UTC, jakirkham commented on .ci_support/linux_64_cdt_namecos6cuda_compiler_version11.0.yaml
> +- cos6
This isn't right

2021-03-23 02:50 UTC, jakirkham commented on .azure-pipelines/azure-pipelines-linux.yml
> -        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
This should have been kept

2021-03-23 02:50 UTC, jakirkham commented on .azure-pipelines/azure-pipelines-linux.yml
> +        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
This shouldn't have been added

2021-03-23 03:00 UTC, jakirkham commented
@conda-forge-admin, please re-render

2021-03-23 03:19 UTC, jakirkham commented
Thanks Isuru! 😄

Should we send a PR to update the migrations? Happy to pick that up 🙂

2021-03-23 03:37 UTC, isuruf commented
> Should we send a PR to update the migrations?

Yes

2021-03-23 05:12 UTC, jakirkham commented
Sounds good. Submitted as PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1368 )

2021-03-23 05:25 UTC, jakirkham approved these changes

2021-03-23 05:26 UTC, isuruf commented
Please don't merge with `use_local: true`. That's only for debugging.

2021-03-23 05:28 UTC, jakirkham commented
Hmm...ok can remove. Thanks for letting me know :)

Don't know much about that command honestly. Is that something we are defining or conda-build is defining?

2021-03-23 05:29 UTC, jakirkham reviewed
Removing `use_local`

2021-03-23 05:29 UTC, jakirkham commented on .ci_support/migrations/cuda110.yaml
> +  use_local: True
```suggestion
```

2021-03-23 05:29 UTC, jakirkham commented on .ci_support/migrations/cuda111_112.yaml
> +  use_local: true
```suggestion
```

2021-03-23 05:30 UTC, jakirkham commented
@conda-forge-admin, please re-render

2021-03-23 05:47 UTC, jakirkham commented on .ci_support/linux_64_cdt_namecos6cuda_compiler_version11.0.yaml
> +- cos6
Hmm...this crept back in after the bot re-rendered. Must be missing something else still

2021-03-23 05:48 UTC, jakirkham commented
@conda-forge-admin, please re-render

2021-03-23 05:51 UTC, jakirkham commented on .ci_support/linux_64_cdt_namecos6cuda_compiler_version11.0.yaml
> +- cos6
This was just because the re-rendering didn't pick up the new pinning change. Should be fixed now

2021-04-21 17:53 UTC, leofang commented
I think this is superseded by #89. I am taking the liberty of closing it. Let me know if I am wrong!

2021-04-21 17:53 UTC, closed without merging